name: ILS
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - backcall=0.2.0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - ipykernel=6.13.0
  - ipython=7.32.0
  - jedi=0.18.1
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - libcxx=13.0.1
  - libffi=3.4.2
  - libsodium=1.0.18
  - libzlib=1.2.11
  - matplotlib-inline=0.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=3.0.2
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.0.4
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pygments=2.11.2
  - pyparsing=3.0.8
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pyzmq=22.3.0
  - readline=8.1
  - setuptools=62.1.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cffi==1.15.0
    - cycler==0.11.0
    - defusedxml==0.7.1
    - fastjsonschema==2.15.3
    - fonttools==4.32.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.2.1
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - notebook==6.4.10
    - numpy==1.21.5
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - pillow==9.1.0
    - prometheus-client==0.14.1
    - pycparser==2.21
    - pyrsistent==0.18.1
    - pytz==2022.1
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sklearn==0.0
    - soupsieve==2.3.2
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - typing-extensions==4.1.1
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0
